defaults:
  - algo_base

rollout_length: 5
epochs: 4
k: 500
hidden_dim: 256
latent_dim: 128
batch_size: 256
gamma: 0.99
env: pen-human-v1
seed: 0
target_ema: 0.005
grad_clip_norm: 10.0
eval_episodes: [0, 10, 100, 200, 400, 1000]
knn_temp: [0.01, 0.1, 0.5, 1.0, 2.0, 10.0, 100.0]