defaults:
  - _self_
  - algo
  - override hydra/launcher: slurm

# wandb
project: CORL
group: knn
name: multistep_model

cluster_checkpointing: True
alt_path:

hydra:
  mode: MULTIRUN
  job:
    chdir: True
    env_set:
      MUJOCO_GL: glfw