defaults:
  - submitit_slurm
timeout_min: 5750
max_num_timeout: 10
submitit_folder: /h/eop/submitit
qos: scavenger
gres: gpu:1
partition: rtx6000,a40,t4v1,t4v2
mem_gb: 64
cpus_per_task: 16
exclude: gpu138,gpu148
setup:
  - "source ~/.bashrc"
  - "module load pytorch2.1-cuda11.8-python3.10; export MUJOCO_PY_BYPASS_LOCK=True; export LD_LIBRARY_PATH=/h/eop/.mujoco/mujoco210/bin:/pkgs/cudnn-8.8/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH=/pkgs/cuda-11.8/extras/CUPTI/lib64/:/usr/lib/nvidia:$LD_LIBRARY_PATH; export MUJOCO_GL=egl; cd /h/eop/in-context-search-rl; source venv/bin/activate; export DISPLAY=0; export PYTHONPATH=/h/eop/in-context-search-rl:$PYTHONPATH"
  - "hostname"
  - "nvidia-smi"